version: '3.8'

services:
  app:
    image: tuanballboo/taprim:latest
    container_name: taprim
    restart: always
    ports:
      - "80:8080"
    environment:
      ConnectionStrings__MyCnn=Server=103.238.235.227;Database=taprim;User Id=sa;Password=Tuananh235;TrustServerCertificate=True;
      ConnectionStrings__Redis=redis:6379
      VietQr__ClientId=7e60dc5f-96e7-4901-a513-db4e4dbcd8c4
      VietQr__ApiKey=a29b57bb-c706-4383-8f29-25a122c888ef

    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_net

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app_net

volumes:
  redis-data:
