version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # 👈 Thêm dòng này
    networks:
      - app_net
      

networks:
  app_net:
    name: app_net
