name: CI/CD Deploy to VPS

on:
  push:
    branches:
      - main   # hoặc nhánh bạn muốn deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: yourdockerhubusername/yourapp:latest

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          docker pull yourdockerhubusername/yourapp:latest
          docker stop yourapp || true
          docker rm yourapp || true
          docker run -d --name yourapp -p 80:80 yourdockerhubusername/yourapp:latest
